# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-19 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionoperation',
            options={'verbose_name': '\u62a5\u8b66\u64cd\u4f5c', 'verbose_name_plural': '\u62a5\u8b66\u64cd\u4f5c'},
        ),
        migrations.RemoveField(
            model_name='action',
            name='host_groups',
        ),
        migrations.RemoveField(
            model_name='action',
            name='hosts',
        ),
        migrations.RemoveField(
            model_name='actionoperation',
            name='msg_format',
        ),
        migrations.AddField(
            model_name='action',
            name='msg_format',
            field=models.TextField(default='Host({hostname},{ip}) service({service_name}) has issue,msg:{msg}', verbose_name='\u6d88\u606f\u683c\u5f0f'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='host',
            field=models.ManyToManyField(blank=True, to='monitor.Host'),
        ),
        migrations.AlterField(
            model_name='actionoperation',
            name='action_type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('script', 'RunScript')], default='email', max_length=64, verbose_name='\u64cd\u4f5c\u7c7b\u578b'),
        ),
    ]
